version: '3.7'

services:
  notifications-api:
    build:
      context: .
      target: dev
    ports:
     - 3030:3030
    volumes:
     - ./:/app
     - /app/node_modules
     - /app/app
    environment:
      DATABASE_URL: postgres://user:pass@postgres:5432/db
    depends_on:
     - postgres

  postgres:
    image: postgres:10.4
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres:/data/db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db

volumes:
 postgres: